### PR TITLE
Fix/mico#762 refactor kafka faas connector

### LINKED ISSUE #762: Refactor kafka-faas-connector
The MessageListener class of the kafka faas connector should be split into logical components (receiving, faas logic, sending, utility functions).

### PR DESCRIPTION
**Pull request by wagnerdk**
# Description

This refactors the MessageListener class and splits the logic into multiple parts. There is now a separate class for message modification, FaaS calls and message sending. Additionally, I refactored some methods and added tests.

# Resolves / is related to

Closes https://github.com/UST-MICO/mico/issues/762

# What is affected by this PR

- [ ] OpenFaaS Function Exchange Format
- [ ] Message Format
- [ ] Documentation ([Doc repository](https://github.com/UST-MICO/docs))

# Checklist

- [X] Ensure that new source files include the [license header](https://github.com/UST-MICO/mico/blob/master/CONTRIBUTING.md#source-file-headers)

### CODE REVIEW

File: src/main/java/io/github/ust/mico/kafkafaasconnector/MessageProcessing/CloudEventManipulator.java [hunk 1]
```diff
@@ -0,0 +1,170 @@
...
+ *
+ * Unless required by applicable law or agreed to in writing,
+ * software distributed under the License is distributed on an
+ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
+ * KIND, either express or implied.  See the License for the
+ * specific language governing permissions and limitations
+ * under the License.
+ */
+
+package io.github.ust.mico.kafkafaasconnector.MessageProcessing;
```
Comment (davidkopp) [inline src/main/java/io/github/ust/mico/kafkafaasconnector/MessageProcessing/CloudEventManipulator.java]: To be consistent the package `MessageProcessing` should be written in lowercase

File: src/main/java/io/github/ust/mico/kafkafaasconnector/MessageProcessing/FaasController.java [hunk 2]
```diff
@@ -0,0 +1,99 @@
...
+    private RestTemplate restTemplate;
+
+    /**
+     * Synchronously call the configured openFaaS function.
+     *
+     * @param cloudEvent the cloud event used as parameter for the function
+     * @return the result of the function call (in serialized form)
+     */
+    public List<MicoCloudEventImpl<JsonNode>> callFaasFunction(MicoCloudEventImpl<JsonNode> cloudEvent) throws MicoCloudEventException {
+        if (!this.openFaaSConfig.isSkipFunctionCall()) {
```
Comment (davidkopp) [inline src/main/java/io/github/ust/mico/kafkafaasconnector/MessageProcessing/FaasController.java]: Personally I prefer to exit a function early to enhance the readability:
```java
if (this.openFaaSConfig.isSkipFunctionCall()) {
    return Collections.singletonList(cloudEvent);
}

try { 
...
```

File: src/main/java/io/github/ust/mico/kafkafaasconnector/MessageProcessing/CloudEventManipulator.java [hunk 3]
```diff
@@ -0,0 +1,170 @@
...
+    /**
+     * Sets the time, the correlationId and the Id field of a CloudEvent message if missing
+     *
+     * @param cloudEvent        the cloud event to send
+     * @param originalMessageId the id of the original message
+     */
+    public void setMissingHeaderFields(MicoCloudEventImpl<JsonNode> cloudEvent, String originalMessageId) {
+
+        setMissingId(cloudEvent);
+        addMissingTime(cloudEvent);
```
Comment (davidkopp) [inline src/main/java/io/github/ust/mico/kafkafaasconnector/MessageProcessing/CloudEventManipulator.java]: to be more consistent, rename it to `setMissingTime`

File: src/test/java/io/github/ust/mico/kafkafaasconnector/MessageListenerTests.java [hunk 4]
```diff
@@ -77,6 +84,15 @@
     @Autowired
     MessageListener messageListener;
 
+    @Autowired
+    FaasController faasController;
```
Comment (davidkopp) [inline src/test/java/io/github/ust/mico/kafkafaasconnector/MessageListenerTests.java]: Proposal: Extract the unit tests that only tests one specific service to its own test class:
- `FaasControllerTests`
- `CloudEventManipulatorTests` 
- `KafkaMessageSenderTests`
- `CloudEventDeserializerTests`

**Review by davidkopp — CHANGES_REQUESTED** [review]

**Review by davidkopp — APPROVED** [review]
